# Site Info
title: Data science
tagline: 'by Yngie'
description: 'blog for textmining'
url: https://yngie-c.github.io
logo: '/public/logo.png'
encoding: utf-8

# Site configurations
gems:
  - jekyll-paginate
markdown: kramdown
kramdown:
  input: GFM
excerpt_separator: "<!-- more -->"
sass:
  style: compressed
  sass_dir: _scss    
paginate: 5
paginate_path: '/blog/page:num'
permalink: pretty
version: 1.0.0

# About/contact
author:
  name: Yngie
  description: <strong>Increscunt animi virescit volnere virtus</strong> by Friedrich Nietzsche
  gravatar: 8dc8eb5fb70460f5da8e678a7cb47b3f # md5 hash of your email address
  contact:
    #linkedin:  https://www.linkedin.com/in/gichanglee/
    github:    https://github.com/Yngie-C
    #facebook:  https://www.facebook.com/gichanglee.84
    #twitter:  <hide>
    #weibo:    <hide>
    instagram :   https://instagram.com/yngie_daily
    #email:    

# Navigation (2nd level links supported)
nav:
  Home:           
    - '/'
  Contents:           
    - '/blog/'
    - { Categories: '/blog/categories/' }
    - { Tags: '/blog/tags/' }
  About:          
    - '/about/'

# Where are tags and categories displayed
tag_page: '/blog/tags/'
category_page: '/blog/categories/'

hero:
  image: https://Yngie-C.github.io/public/img/pic.JPG
  caption: Original Artwork &copy; Pablo Picasso. Girl before a Mirror. Boisgeloup, March 1932. Oil on canvas

# Puglins
mathjax: true # whether support mathjax
#google_analytics_token: 'UA-93172815-1' # leave blank if you don't want google analytics
#disqus_short_name: 'ratsgo-github-io' # leave blank if you don't want disqus

